### ISSUE TITLE
Windows build fail with Msys2

### ISSUE THREAD

**Issue by BigslimVdub** [aeonix/aeon-gui#15]
./build.sh fail : https://paste.fedoraproject.org/paste/JU8dZohXJVSRpDKrmeeZ8Q

./get_libwallet_api.sh fail logs : https://paste.fedoraproject.org/paste/tFt0DZufKbQ97mB0CXtNMg

does not build GUI
Windows 10

**Comment by stoffu** [comment]
The build log from get_libwallet_api.sh seems successful. The other build log contains an error message

```
make[1]: execvp: /C/msys64/mingw64/bin/qmlcachegen.exe: Bad address
```

which I have never seen before. I have no idea how to fix it. You should be able to reproduce the same error with the Monero GUI, so please open a ticket in the Monero GUI bug tracker. Hopefully someone will be able to answer it.

**Comment by BigslimVdub** [comment]
Yes libeallet api.sh only builds daemon and rpc just like the issue on OS X. I will try to clone monero and get logs if it fails.

**Comment by BigslimVdub** [comment]
I see that msys does have QMLcachegen in the specified folder, but I noticed that qmlcache_loader.cpp is not generated.
```
g++ -c -fno-keep-inline-dllexport -fPIC -fstack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wformat -Wformat-security -fstack-protector -fstack-protector-strong -O2 -std=gnu++11 -Wall -W -Wextra -fexceptions -mthreads -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I../../aeon-gui -I. -I../monero/include -I../src/libwalletqt -I../src/QR-Code-generator -I../src -I../monero/src -I../../../../mingw64/include/QtQuick -I../../../../mingw64/include/QtWidgets -I../../../../mingw64/include/QtGui -I../../../../mingw64/include/QtQml -I../../../../mingw64/include/QtNetwork -I../../../../mingw64/include/QtCore -Irelease -I../../../../mingw64/include -I../../../../mingw64/share/qt5/mkspecs/win32-g++  -o release/pages_TxKey_qml.o release/pages_TxKey_qml.cpp
/C/msys64/mingw64/bin/qmlcachegen.exe --resource-file-mapping=C:/msys64/home/*/aeon-gui/qml.qrc=C:/msys64/home/*/aeon-gui/build/qml_qmlcache.qrc -o release/qmlcache_loader.cpp ../qml.qrc
```
 I have combed through the maker files and am unable to find where this is generated from, but the file is indeed not where if is being called from in the release folder that is why it is getting the 127 error for bad address. QT had this issue from msys32 compiling of QT5.11 from a google search so unsure if it is related to QT compiling error from msys2 but I have re-installed qt through msys and it did not fix the issue. 
![qmlcache_loader cpp not created](https://user-images.githubusercontent.com/30030687/45589129-07580d00-b8e6-11e8-8ada-6115510555c5.PNG)

**Comment by BigslimVdub** [comment]
GUI builds with latest msys64 packages including qt 5.12.0-1-any. 

Don’t forget “cd build” and “make deploy” after building packages.
