### ISSUE TITLE
Aeon GUI does not allow ringsize 0 transactions but CLI does

### ISSUE THREAD

**Issue by BigslimVdub** [aeonix/aeon-gui#17]
The latest GUI 12.6 does not allow ring size 0 transactions, the slider bar does not move to 0, 1 is the lowest. CLI wallet 12.6 allows ring size 0 transactions. Although this 0 mixin transaction removal is being discussed on Reddit:
 ( https://www.reddit.com/r/Aeon/comments/9mwj5p/removal_of_0_mixing_as_and_when_bulletproofs/ ) , I am unsure as to why the GUI already has this removed and only Ring size 1 or 3 and higher is allowed. 

If we are going to remove ring size 0,1,2,3,4 when we activate bulletproofs and ring CT next, I think we can ignore this issue for now and just verify the ring sizes are disabled with the next pre-release testing. If we plan to not remove ring size 0 we need to fix this issue on gui wallet. 

Please discuss.

**Comment by stoffu** [comment]
> the slider bar does not move to 0, 1 is the lowest.

1 is the ring size, which means 0 mixin. This issue is nonexistent.
