### ISSUE TITLE
GUI will not connect to remote node if switching to remote from local unless restarting GUI

### ISSUE THREAD

**Issue by BigslimVdub** [aeonix/aeon-gui#23]
OS : OSX 10.13.6
Also known issue on Windows 10

Build version: Latest 12.9 point release

Issue:
When an incorrect remote node IP address is entered and daemon can not connect prompting "local node starting in ***sec", if user selects use remote node and changes to correct IP address, daemon will not connect to that IP until GUI is restarted upon which it connects the first try to the remote node. 

If on OSX after GUI hangs up and user closes program, the program crashes and attempts to send crash report. 

If on Windows GUI does close normally. 

If user is using Local Daemon and switches to remote node and clicks connect, GUI will also hang up until restarted in which it connects fine so long as correct IP is used.

**Comment by BigslimVdub** [comment]
Posting some upstream merges that should fix some various hang issues:

https://github.com/monero-project/monero-gui/pull/2226

https://github.com/monero-project/monero-gui/pull/2223

https://github.com/monero-project/monero-gui/pull/1015

https://github.com/monero-project/monero-gui/issues/1261

**Comment by stoffu** [comment]
I was able to reproduce the issue (set the remote node IP to an incorrect value, then set it back to a correct one, resulting in being unable to connect) on macOS, actually also with the Monero GUI. The suggested PRs 2223/2226 don't seem to fix the issue.

PR 1015 was already included at the time of the last rebase fork.

**Comment by BigslimVdub** [comment]
I did ask DSC about it a while ago however did not get a response back. Possibly if you could ping him about it. It’s not critical for 13.0 release as there is a workaround but none the less needs attention at some point.

**Comment by BigslimVdub** [comment]
Still, the issue is present on v0.13.1.0 release on OSX.

**Comment by BigslimVdub** [comment]
This is resolved in v0.14.2.1 release
