### ISSUE TITLE
v0.12.0 Sophia missing `start-low-graphics-mode` batch file in win x64 release

### ISSUE THREAD

**Issue by BigslimVdub** [aeonix/aeon-gui#4]
Batch file is missing. Can not start GUI.exe on windows 10, it crashes. 

Copy-Paste batch file from 1.8.1 beta directory and gui opens properly.

**Comment by stoffu** [comment]
Sorry, it was my mistake sending a wrong file to smooth. Now it should be fixed.

**Comment by BigslimVdub** [comment]
Did you update the release file? I can check

**Comment by iamsmooth** [comment]
Yes it is updated

**Comment by BigslimVdub** [comment]
![aeon gui no low graphics bat](https://user-images.githubusercontent.com/30030687/40626490-81c33c72-627e-11e8-90df-a0c15b0a428f.png)

Just rechecked and its not in the X64 zip still. Checked downloading on 2 different computers and its not there. Also did a search and its not in the zip anywhere.

**Comment by BigslimVdub** [comment]
Just checked and it **is** in the **SOURCE** zip, but not the release zip for windows.

**Comment by BigslimVdub** [comment]
rechecked release and Batch file is now in the zip for Windows x64
