### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by publicocean0** [aeonix/aeon-gui#7]
_chrono -lboost_program_options -lssl -llmdb -lcrypto -Wl,-Bdynamic -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
/usr/bin/x86_64-linux-gnu-ld: impossibile trovare -lwallet_merged
/usr/bin/x86_64-linux-gnu-ld: impossibile trovare -lepee
/usr/bin/x86_64-linux-gnu-ld: impossibile trovare -leasylogging
/usr/bin/x86_64-linux-gnu-ld: impossibile trovare -llmdb
collect2: error: ld returned 1 exit status
Makefile:292: recipe for target 'release/bin/aeon-wallet-gui' failed
make: *** [release/bin/aeon-wallet-gui] Error 1

**Comment by stoffu** [comment]
Probably you failed to build the Monero main library (libwallet_merged). Run get_libwallet_api.sh and paste the full build log to https://paste.debian.net/ or http://fpaste.org/

**Comment by publicocean0** [comment]
i solved using cli version
